[project]
name = "school-tools"
version = "0.1.0"
description = "School Tools API backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "markdown>=3.10.3",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sentry-sdk>=2.66.1",
    "uvicorn>=0.52.1",
]
