import type { LucideIcon } from "lucide-react"
import {
  Atom,
  Banknote,
  Beaker,
  Book,
  BookMarked,
  BookOpen,
  Brush,
  Building2,
  Calculator,
  CaseSensitive,
  ClipboardList,
  ClipboardPen as ClipboardPencil,
  Code,
  DraftingCompass,
  Dna,
  Dumbbell,
  Feather,
  FlaskConical,
  Footprints,
  Gavel,
  Globe,
  Globe2,
  GraduationCap,
  History,
  Landmark,
  Languages,
  Library,
  Map,
  MapPinned,
  Medal,
  MicVocal,
  Microscope,
  Music,
  NotebookPen,
  NotebookTabs,
  Palette,
  Pi,
  Quote,
  Ruler,
  Ruler as RulerMeasure,
  Scale,
  School,
  Scroll,
  ScrollText,
  Sigma,
  SquareFunction,
  TestTube,
  Timer,
  TreePine,
  Trophy,
} from "lucide-react"

export const SUBJECT_ICONS: Record<string, LucideIcon> = {
  BookOpen,
  BookMarked,
  Book,
  Library,
  GraduationCap,
  School,
  NotebookPen,
  NotebookTabs,
  ScrollText,
  ClipboardPencil,
  ClipboardList,
  Sigma,
  SquareFunction,
  Pi,
  Calculator,
  DraftingCompass,
  Ruler,
  RulerMeasure,
  FlaskConical,
  Atom,
  Dna,
  Microscope,
  TestTube,
  Beaker,
  Globe,
  Globe2,
  Map,
  MapPinned,
  TreePine,
  Languages,
  Scroll,
  Feather,
  Quote,
  History,
  Landmark,
  Building2,
  Banknote,
  Scale,
  Gavel,
  CaseSensitive,
  Palette,
  Brush,
  Music,
  MicVocal,
  Dumbbell,
  Trophy,
  Medal,
  Footprints,
  Timer,
  Code,
}

export const DEFAULT_SUBJECT_ICON = "BookOpen"

export function getSubjectIcon(icon?: string | null): LucideIcon {
  return (icon && SUBJECT_ICONS[icon]) || SUBJECT_ICONS[DEFAULT_SUBJECT_ICON]
}

export function getSubjectIcons(): Array<{ name: string; Icon: LucideIcon }> {
  return Object.entries(SUBJECT_ICONS).map(([name, Icon]) => ({ name, Icon }))
}